### PR TITLE
Fix/ missing display variable and permission

### LINKED ISSUE #162: fix : permission and missing display variable
## Describe the issue
 Petit fix à apporter dans le projet

## Resource request
Access to API doc

## Definition of done
Permission Manager:
- [ ] Créer une team
- [ ] Créer une mission
- [ ] Edit une team
- [ ] Edit une mission
- [ ] Delete a team
- [ ] Delete a mission
----
Permission Pentester:
- [ ] Créer une note
- [ ] Créer un nmap
- [ ] Créer une vulnérability
- [ ] Edit une note
- [ ] Edit une vulnérabilité
- [ ] Supprimier une note
- [ ] Supprimer une vulnérabilté
----
Variable manquante à afficher:
- [ ] Nom du pentester dans une note
- [ ] Nom de la team dans mission main
- [x] nom de la mission dans vulnérabilté
- [ ] Nom de mission in team list
----
Autre:
- [ ] Lier la page login avec register et inversement
- [x] Faire le bouton déconnexion
- [ ] Delete action colonne in teamlist if not manager

### PR DESCRIPTION
**Pull request by Ananane**
# Description

Fix affichage of side bar, redirection login to signup and fix font on span component. 

# Fixes

Specify which issue this PR targets, like so:

- fixes #162 

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Breaking changes

Please complete this section if any breaking changes have been made, otherwise delete it.

# Checklist

- [ ] I have assigned this PR to myself
- [ ] I have added @vrn-sh/members to the reviewers, or specific members of the team
- [ ] I have added the needed labels
- [ ] I have tested this code
- [ ] I have added / updated tests (unit / functionals / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)

# Additional comments

Please post additional comments in this section if you have them, otherwise delete it.

### CODE REVIEW

File: web/src/pages/Dashboard/SubDashboards/Vulnerability.tsx [hunk 1]
```diff
@@ -77,7 +77,7 @@ export default function Vulnerability() {
                 for (let i = 0; i < data.data.results.length; i += 1) {
```
Comment (lambdina) [inline web/src/pages/Dashboard/SubDashboards/Vulnerability.tsx:77]: Please correct linter errors.

**Review by lambdina — APPROVED** [review]
All good but please correct linter errors before merge.

**Review by claraxuxu — APPROVED** [review]
